spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties.hibernate.hbm2ddl.auto: create
    showSql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true