spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: redis
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://mysql:3306/investment?characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver